name: Flush

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
     - cron: '2 * * * *' #ogni minuto
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild Sito GitHub
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
